import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import LeftSideBar from "@/components/leftSideBar";
import RightSideBar from "@/components/rightSideBar";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/actions/user";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const userId = cookieStore.get("user_id")?.value;

  if (!userId) redirect("/sign-in");

  const user = await getCurrentUser(userId);

  if (!user) redirect("/sign-in");

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}>
        {/* Background layer */}
        <div className="grid-background"/>

        {/* Foreground content */}
        <div className="flex justify-between max-w-6xl mx-auto relative z-10">
          {/* Left Sidebar */}
          <div className="hidden sm:inline h-screen sticky top-0">
            <LeftSideBar user={user} />
          </div>

          {/* Main content */}
<main className="w-2xl flex-1">{children}</main>

          {/* Right Sidebar */}
          <div className="lg:flex-col p-3 h-screen  hidden lg:flex w-[24rem]">
            <RightSideBar />
          </div>
        </div>
      </body>
    </html>
  );
}
